# Generated by Django 3.1.2 on 2022-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.TextField(verbose_name='Изображение')),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
        ),
    ]
